version: '3.4'

services:
  workspace:
    build:
      context: ./
      target: dev
    volumes:
      - .:/workspace
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:9.6-alpine
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
